---
- name: Aliasları listeyelerek home dizin altına bir dosyaya yazar
  hosts: all
#  become_user: root
#  become_method: su
  become: yes
  gather_facts: True
  tasks:
     - name: alias listeleme ve kayıt
#       shell: alias >> /home/osboxes/aliaslar.txt
       raw: "bash -ic alias >/root/aliaslar.txt"  # debug yapmak isterseniz >>/home/osboxes/aliaslar.txt ifadesini kaldırıp debug ve altındaki satırdan yorum işaretini kaldırınız.
       register: command_output
#     - debug:
#         var: command_output.stdout_lines
