---
- name: Copy a ls23sistem.pub key
  ansible.builtin.copy:
    src: /home/ls23sistem/.ssh/authorized_keys
    dest: /home/ls23sistem/backups/ls23sistem.pub
    owner: ls23sistem
    group: ls23sistem
    mode: 0600
    backup: yes
    remote_src: yes

- name: Copy a ls23web.pub key
  ansible.builtin.copy:
    src: /home/ls23web/.ssh/authorized_keys
    dest: /home/ls23sistem/backups/ls23web.pub
    owner: ls23web
    group: ls23web
    mode: 0600
    backup: yes
    remote_src: yes

- name: Copy a ls23th.pub key
  ansible.builtin.copy:
    src: /home/ls23th/.ssh/authorized_keys
    dest: /home/ls23sistem/backups/ls23th.pub
    owner: ls23th
    group: ls23th
    mode: 0600
    backup: yes
    remote_src: yes

- name: Copy a ls23sp.pub key
  ansible.builtin.copy:
    src: /home/ls23sp/.ssh/authorized_keys
    dest: /home/ls23sistem/backups/ls23sp.pub
    owner: ls23sp
    group: ls23sp
    mode: 0600
    backup: yes
    remote_src: yes

- name: Copy a ls23bank.pub key
  ansible.builtin.copy:
    src: /home/ls23bank/.ssh/authorized_keys
    dest: /home/ls23sistem/backups/ls23bank.pub
    owner: ls23bank
    group: ls23bank
    mode: 0600
    backup: yes
    remote_src: yes

- name: Copy a ls23root.pub key
  ansible.builtin.copy:
    src: /root/.ssh/authorized_keys
    dest: /home/ls23sistem/backups/ls23root.pub
    owner: root
    group: root
    mode: 0600
    backup: yes
    remote_src: yes
