---
- name: "Quick Fix - Disable {{ package }} - Debian-ish systems"
  apt:
    name: '{{ package }}'
    state: absent
    purge: yes
  with_items:
    - nis
    - sudosh
    - snoopy
    - xinetd
    - telnetd
    - rsh-redone-server
    - rsh-server
    - tftpd-hpa
    - atftpd
    - yp-tools
    - tftpd
    - sudosh
    - inetd
    - ypserv
    - telnet-server
    - prelink
    - telnet
    - socat
    - nc
    - netcat
    - knockd
    - cockpit
    - nyancat
  when: ansible_distribution in ['Debian', 'Ubuntu']
  ignore_errors: true

- name: Remove useless packages from the cache
  apt:
    autoclean: yes
  when: ansible_distribution in ['Debian', 'Ubuntu']
  ignore_errors: true

- name: Remove dependencies that are no longer required
  apt:
    autoremove: yes
  when: ansible_distribution in ['Debian', 'Ubuntu']
  ignore_errors: true

- name: Apt - Removes all packages from the package cache
  apt:
    clean: true
  when: ansible_distribution in ['Debian', 'Ubuntu']
  ignore_errors: true
