---
- name: "Quick Fix - Disable {{ package }} - Debian-ish systems"
  when: ansible_distribution in ['Debian', 'Ubuntu']
  apt:
    name: '{{ package }}'
    state: absent
    purge: yes
#  ignore_errors: yes
#  when: ansible_distribution in ['Debian', 'Ubuntu']
  with_items:
    - nis
    - sudosh
    - snoopy
    - xinetd
    - telnetd
    - rsh-redone-server
    - rsh-server
    - tftpd-hpa
    - atftpd
    - yp-tools
    - tftpd
    - sudosh
    - inetd
    - ypserv
    - telnet-server
    - prelink
    - telnet
    - cockpit

- name: Remove useless packages from the cache
  apt:
    autoclean: yes
  when: ansible_distribution in ['Debian', 'Ubuntu']

- name: Remove dependencies that are no longer required
  apt:
    autoremove: yes
  when: ansible_distribution in ['Debian', 'Ubuntu']

- name: Apt - Removes all packages from the package cache
  command: apt-get clean
  when: ansible_distribution in ['Debian', 'Ubuntu']
