---
####### ansible_user .ssh managment

- name: "Access - Upload Public ssh key - correct folder needs to be in place {{secops_user}}"
  file:
    state: directory
    path: "/home/{{secops_user}}/.ssh"
    recurse: yes
    owner: "{{secops_user}}"
    group: "{{secops_user}}"
    mode: "0700"

- name: "Access - Push Public ssh key {{secops_user}}"
  authorized_key:
    user: "{{secops_user}}"
    state: present
    key: "{{ lookup('file', '../templates/ls23sistem.pub') }}"

#- name: "Access - Push Public ssh key {{secops_user}}"
#  copy:
#    src: "../templates/ls23sistem.pub"
#    dest: "/home/{{secops_user}}/.ssh/"
#    owner: "{{secops_user}}"
#    group: "{{secops_user}}"
#    mode: "0600"


####### web user ssh managment

- name: "Access - Upload Public ssh key - correct folder needs to be in place {{web_user}}"
  file:
    state: directory
    path: "/home/{{web_user}}/.ssh"
    recurse: yes
    owner: "{{web_user}}"
    group: "{{web_user}}"
    mode: "0700"

- name: Access - Push Public ssh key
  authorized_key:
    user: "{{web_user}}"
    state: present
    key: "{{ lookup('file', '../templates/ls23web.pub') }}"

#- name: "Access - Push Public ssh key {{web_user}}"
#  copy:
#    src: "../templates/ls23web.pub"
#    dest: "/home/{{web_user}}/.ssh/"
#    owner: "{{web_user}}"
#    group: "{{web_user}}"
#    mode: "0600"


####### th user .ssh managment

- name: "Access - Upload Public ssh key - correct folder needs to be in place {{th_user}}"
  file:
    state: directory
    path: "/home/{{th_user}}/.ssh"
    recurse: yes
    owner: "{{th_user}}"
    group: "{{th_user}}"
    mode: "0700"

- name: "Access - Push Public ssh key {{th}}"
  authorized_key:
    user: "{{th_user}}"
    state: present
    key: "{{ lookup('file', '../templates/ls23th.pub') }}"

#- name: "Access - Push Public ssh key {{th_user}}"
#  copy:
#    src: "../templates/ls23th.pub"
#    dest: "/home/{{th_user}}/.ssh/"
#    owner: "{{th_user}}"
#    group: "{{th_user}}"
#    mode: "0600"


####### root .ssh managment

- name: "Access - Upload Public ssh key - correct folder needs to be in place root"
  file:
    state: directory
    path: "/root/.ssh"
    recurse: yes
    owner: "root"
    group: "root"
    mode: "0700"

- name: Access - Push Public ssh key root
  authorized_key:
    user: root
    state: present
    key: "{{ lookup('file', '../templates/ls23root.pub') }}"

#- name: "Access - Push Public ssh key root"
#  copy:
#    src: "../templates/ls23root.pub"
#    dest: "/root/.ssh/"
#    owner: "root"
#    group: "root"
#    mode: "0600"


####### g5_user .ssh managment

- name: "Access - Upload Public ssh key - correct folder needs to be in place {{g5_user}}"
  file:
    state: directory
    path: "/home/{{g5_user}}/.ssh"
    recurse: yes
    owner: "{{g5_user}}"
    group: "{{g5_user}}"
    mode: "0700"

- name: "Access - Push Public ssh key {{g5_user}}"
  authorized_key:
    user: "{{g5_user}}"
    state: present
    key: "{{ lookup('file', '../templates/ls235g.pub') }}"

#- name: "Access - Push Public ssh key {{g5_user}}"
#  copy:
#    src: "../templates/ls23g5.pub"
#    dest: "/home/{{g5_user}}/.ssh/"
#    owner: "{{g5_user}}"
#    group: "{{g5_user}}"
#    mode: "0600"


#- name: "Access - Push Public ssh key {{bank_user}}"
#  copy:
#    src: "../templates/ls23bank.pub"
#    dest: "/home/{{bank_user}}/.ssh/"
#    owner: "{{bank_user}}"
#    group: "{{bank_user}}"
#    mode: "0600"

#değiştirildi.
#- name: "Access - Push Public ssh key {{th_user}}"
#  template:
#    src: "../templates/ls23thr.pub.j2"
#    dest: "/home/{{th_user}}/.ssh"
#    user: "{{th_user}}"
#    state: present
#    key: "{{ lookup('file', '../keys/ls23ahtapot.pub') }}"
#    owner: "{{ th_user}}"
#    group: "{{ th_user }}"
#    mode: 640
#
#- name: Access - Push Public ssh key
#  authorized_key:
#    user: "{{th_user}}"
#    state: present
#    key: "{{ lookup('file', '../templates/ls21th.pub') }}"
#
#- name: "File Permissions - home directory .ssh permissions"
#  shell: chown -R "{{th_user}}":"{{th_user}}" /home/{{th_user}}/.ssh
#  shell: chmod 600 /home/{{th_user}}/.ssh/ls21th.pub
