---
# LS21 Linux Operation Security
# Selin Akbuğa
#  Configure basics of linux machines: users login root  nopasswd-passwordless 

- name: "Authentication - sudo - NOPASSWD ALL for users  (RedHat-ish)"
  lineinfile:
    path: /etc/sudoers
    state: present
    regexp:  '^%wheel\s'
    line: '%wheel ALL=(ALL) NOPASSWD: ALL'   
  when: ansible_distribution in ['RedHat', 'CentOS', 'AlmaLinux', 'Scientific']

- name: "Authentication - sudo - NOPASSWD ALL for users (Debian-ish)"
  lineinfile:
    path: /etc/sudoers
    state: present
    regexp:  '^%sudo\s'
    line: '%sudo   ALL=(ALL:ALL) NOPASSWD: ALL'
  when: ansible_distribution in ['Debian', 'Ubuntu']
