---
- name: Update repositories cache and install packages
  ansible.builtin.apt:
    update_cache: true
    pkg:
      - rsyslog
      - curl
      - lsb-release
  ignore_errors: true

- name:
  shell: lsb_release -rs
  register: release

- name: Get packages-microsoft-prod.deb file
  get_url:
    url: 'https://packages.microsoft.com/config/ubuntu/{{ release.stdout_lines[0] }}/packages-microsoft-prod.deb'
    dest: /opt/packages-microsoft-prod.deb
    mode: '0755'
  ignore_errors: true

- name: Install the packages-microsoft-prod.deb package
  ansible.builtin.apt:
    deb: /opt/packages-microsoft-prod.deb
  ignore_errors: true

- name: Update repositories cache and install sysmonforlinux package
  ansible.builtin.apt:
    update_cache: true
    name: sysmonforlinux
  ignore_errors: true

- name: Get files
  get_url:
    url: "http://{{ IP }}:{{ PORT }}/linux_sysmon_config_KR.xml"
    dest: /opt/linux_sysmon_config_KR.xml
    mode: '0755'
      
# - name: Download sysmonconfig-export.xml
#   get_url:
#     url: https://raw.githubusercontent.com/SwiftOnSecurity/sysmon-config/master/sysmonconfig-export.xml
#     dest: /opt/sysmonconfig-export.xml

- name: Accept EULA
  ansible.builtin.shell:
    cmd: sysmon -accepteula -i /opt/linux_sysmon_config_KR.xml
  ignore_errors: true

- name: Start rsyslog
  ansible.builtin.systemd:
    name: rsyslog
    state: started
