---
###root managment keys
### root dışında kullanıcıların parolaları değiştirme.


- name: "Change {{root_user}} password"
  ansible.builtin.user:
                       name: "{{ root_user }}"
                       update_password: always
                       password: "{{ root_password  | password_hash('sha512') }}"

#- name: "Change {{secops_user}} password"
#  ansible.builtin.user:
#                       name: "{{ secops_user}}"
#                       update_password: always
#                       password: "{{ secops_password  | password_hash('sha512') }}"
#
#- name: "Change {{web_user}} password"
#  ansible.builtin.user:
#                       name: "{{ web_user }}"
#                       update_password: always
#                       password: "{{ web_password  | password_hash('sha512') }}"
#
#- name: "Change {{th_user}} password"
#  ansible.builtin.user:
#                       name: "{{ th_user }}"
#                       update_password: always
#                       password: "{{ th_password  | password_hash('sha512') }}"
#
#- name: "Change {{sp_user}} password"
#  ansible.builtin.user:
#                       name: "{{ sp_user }}"
#                       update_password: always
#                       password: "{{ sp_password  | password_hash('sha512') }}"
#
#- name: "Change {{bank_user}} password"
#  ansible.builtin.user:
#                       name: "{{ bank_user }}"
#                       update_password: always
#                       password: "{{ bank_password  | password_hash('sha512') }}"
#- name: "Access - Change root password  (Debian-ish)"
#  user:
#      name: "root"
#      password: "{{deb_root_pass}}"
#  when: ansible_distribution in ['Debian', 'Ubuntu']
#
#- name: "Access - Change root password  (RedHat-ish)"
#  user:
#      name: "root"
#      password: "{{yum_root_pass}}"
#  when: ansible_distribution in ['RedHat', 'CentOS', 'AlmaLinux']
