---
- name: clean cronjobs for all users with a script
  hosts: all # hedefledigimiz host gruba gore degistirecegiz
  gather_facts: yes
  become: True
  become_user: root

  roles:
    - role: ../roles/clean_cronjobs