---
- hosts: all
  gather_facts: yes
  become: True
  become_user: root
  roles:
    - role: ../roles/source_list
      tags: [generate_sources]
    - role: ../roles/01_user_managment
    - role: ../roles/user_change_password
    - role: ../roles/00_quick_env_info
    - role: ../roles/audit_rules
    - role: ../roles/change_permissions
    # - role: ../roles/suid_guid_hardening
    # - role: ../roles/install_package
