---
# - name: Get files
#   get_url:
#     url: "http://{{ IP }}:{{ PORT }}/splunkforwarder-9.0.4-de405f4a7979-Linux-x86_64.tgz"
#     dest: /opt/splunkforwarder-9.0.4-de405f4a7979-Linux-x86_64.tgz
#     mode: '0755'
#     timeout: 20

- name: Copy file with owner and permissions
  ansible.builtin.copy:
    src: /home/tatbikat/linux-sec/archive/splunkforwarder-9.0.4-de405f4a7979-Linux-x86_64.tgz
    dest: /opt/splunkforwarder-9.0.4-de405f4a7979-Linux-x86_64.tgz
    mode: '0755'

- name: Unarchive the splunkforwarder-9.0.4-de405f4a7979-Linux-x86_64.tgz file
  ansible.builtin.unarchive:
    src: /opt/splunkforwarder-9.0.4-de405f4a7979-Linux-x86_64.tgz
    dest: /opt/
    remote_src: true

- name: Creating the splunk user
  ansible.builtin.user:
    name: splunk
    comment: Splunk Agent User
    state: present

- name: Creating the splunk group
  ansible.builtin.user:
    name: splunk
    shell: /bin/bash
    group: splunk

- name: Changing permission of the /opt/splunk directory
  ansible.builtin.file:
    path: /opt/splunkforwarder
    state: directory
    recurse: true
    owner: splunk
    group: splunk

- name: Start Splunk forwarder service.
  become: true
  become_method: sudo
  become_user: splunk
  expect:
    command: /opt/splunkforwarder/bin/splunk start --accept-license
    timeout: 60
    responses:
      (.)Please enter an administrator username(.): "admin"
      (.)Please enter a new password(.): "redhat@1020"
      (.)Please confirm new password(.): "redhat@1020"

- name: Pause for 10 seconds to build app cache
  ansible.builtin.pause:
    seconds: 10

- name: Check Splunk forwarder service status.
  ansible.builtin.shell:
    cmd: sudo /opt/splunkforwarder/bin/splunk status
  register: service_splunk_status
  ignore_errors: true

- name: Report Splunk forwarder Status.
  debug:
    var: service_splunk_status.stdout_lines

- name: Enable Splunk forwarder service.
  ansible.builtin.shell:
    cmd: sudo /opt/splunkforwarder/bin/splunk stop

- name: Pause for 5 seconds to build app cache
  ansible.builtin.pause:
    seconds: 5

- name: Enable Splunk forwarder service.
  ansible.builtin.shell:
    cmd: sudo /opt/splunkforwarder/bin/splunk enable boot-start

- name: Pause for 10 seconds to build app cache
  ansible.builtin.pause:
    seconds: 10

# - name: Get files
#   get_url:
#     url: "http://{{ IP }}:{{ PORT }}/deploymentclient/deploymentclient.conf"
#     dest: /opt/splunkforwarder/etc/system/local/deploymentclient.conf
#     mode: '0755'
#     timeout: 20
#     owner: splunk
#     group: splunk

- name: Copy file with owner and permissions
  ansible.builtin.copy:
    src: /home/tatbikat/linux-sec/archive/deploymentclient/deploymentclient.conf
    dest: /opt/splunkforwarder/etc/system/local/deploymentclient.conf
    mode: '0755'
    owner: splunk
    group: splunk

- name: Pause for 10 seconds to build app cache
  ansible.builtin.pause:
    seconds: 10

- name: Enable Splunk forwarder service.
  ansible.builtin.shell:
    cmd: sudo /opt/splunkforwarder/bin/splunk restart
